---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jupyter-2
  namespace: argo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/red512/tsunami-lab-gitops.git
    targetRevision: HEAD
    path: gitops/environments/staging/jupyter-2
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true