apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-2
  namespace: jupyter-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-2
  template:
    metadata:
      labels:
        app: jupyter-2
    spec:
      containers:
      - name: jupyter-2
        image: jupyter/base-notebook
        ports:
        - containerPort: 8888
        args: ["start-notebook.sh", "--NotebookApp.token=''"]
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
