apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-1
  namespace: jupyter-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter-1
  template:
    metadata:
      labels:
        app: jupyter-1
    spec:
      containers:
      - name: jupyter-1
        image: jupyter/base-notebook
        ports:
        - containerPort: 8888
        args: ["start-notebook.sh", "--NotebookApp.token=''"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "256m"
            # memory: "256Mi"
            # cpu: "500m"
