apiVersion: v1
kind: Service
metadata:
  name: jupyter-1-service
  namespace: webapp-flask-fe
spec:
  type: LoadBalancer
  # type: NodePort
  selector:
    app: jupyter-1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
